### ISSUE TITLE
Не запускается!

### ISSUE THREAD

**Issue by Frisk2010** [gODeaLoAple/Zuma#1]
Не запускается! Ошибка:：
PS D:\zuma-game-master> & D:/python3.11.1/python.exe d:/Zuma-master/zuma.py
Traceback (most recent call last):
  File "d:\Zuma-master\zuma.py", line 4, in <module>
    from gui.main_window import MainWindow
  File "d:\Zuma-master\gui\__init__.py", line 1, in <module>
    import gui.main_window
  File "d:\Zuma-master\gui\main_window.py", line 3, in <module>       
    from gui.application_window import ApplicationWindow
  File "d:\Zuma-master\gui\application_window.py", line 5, in <module>
    from gui.windows import *
  File "d:\Zuma-master\gui\windows\__init__.py", line 1, in <module>  
    from gui.windows.start_window import StartWindow
  File "d:\Zuma-master\gui\windows\start_window.py", line 4, in <module>
    from gui import utils
  File "d:\Zuma-master\gui\utils.py", line 29, in <module>
    class Images:
  File "d:\Zuma-master\gui\utils.py", line 31, in Images
    BALLS = extract_balls(os.path.join(IMAGES_DIR, "entities", "balls.png"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Zuma-master\gui\utils.py", line 26, in extract_balls
    return [balls.copy(x * x_step, y * y_step, x_step, y_step) for x in range(columns) for y in range(rows)]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Zuma-master\gui\utils.py", line 26, in <listcomp>
    return [balls.copy(x * x_step, y * y_step, x_step, y_step) for x in range(columns) for y in range(rows)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  copy(self, rect: QRect = QRect()): argument 1 has unexpected type 'float'
  copy(self, x: int, y: int, w: int, h: int): argument 1 has unexpected type 'float'

**Comment by gODeaLoAple** [comment]
Привет. Это странно, должно работать. В проекте ничего не менялось?

**Comment by Frisk2010** [comment]
> Привет.Это странно, должно работать.В проекте ничего не менялось?

Теперь все в порядке, для запуска требуется определенная версия python, 3.11, которую я использую, не очень хороша, требуется 3.8
